services:
  sonic_ai:
    build: .
    command: python manage.py runserver 0.0.0.0:3333
    volumes:
      - .:/app
    ports:
      - "3333:3333"
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DJANGO_SETTINGS_MODULE=api.settings
      - OLLAMA_HOST=https://395d-197-230-122-197.ngrok-free.app
      - MISP_URL=https://d328-197-230-122-197.ngrok-free.app
      - MISP_KEY=DDL2X1VilJzgLvDSo58OMhVHYlnRRg9ShHaiadpA
      # - MISP_KEY=VfmHZTrVA3QJdKuB1z4odhXnx935FPObRJ2zRdD6
      - AGENTOPS_API_KEY=874b2348-5d0b-4189-9c9f-0c4910f056a4
      - ENV=dev

