version: "3.3"

services:
  sonic_ai:
    build: .
    command: python manage.py runserver 0.0.0.0:3333
    volumes:
      - .:/app
    ports:
      - "3333:3333"
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1,ngrok-free.app,sonic-protect.network,0.0.0.0
      - DJANGO_SETTINGS_MODULE=api.settings
      - OLLAMA_HOST=https://ollama-cluster1.oualil.me
      - MISP_URL=https://e71d-197-230-122-195.ngrok-free.app
      - MISP_KEY=DDL2X1VilJzgLvDSo58OMhVHYlnRRg9ShHaiadpA
      - AGENTOPS_API_KEY=874b2348-5d0b-4189-9c9f-0c4910f056a4
      - ENV=dev
      - VIRUSTOTAL_API_KEY=08c94f232e2dde41119539bd1aaa214d2828c4a49f13b860fe385dc84a4955ab
      - LANGCHAIN_API_KEY=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
      - ES_URL=https://elasticsearch-cluster1.oualil.me
      - ES_PASSWORD=O*yFNqBmrZNiX9rXt8U5
      - LANGFUSE_PUBLIC_KEY=pk-lf-0da9fe8d-2606-42a2-9c05-32046d1a3caa
      - LANGFUSE_SECRET_KEY=sk-lf-2530fc29-3217-4aab-a103-ef6a3cafd36e
      - LANGFUSE_API_URL=https://langfuse-cluster1.oualil.me
      - LANGFUSE_ENABLE_TRACING=False # Set to True to enable tracing
