language: python
os: linux
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
jobs:
  include:
    # https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
    # https://travis-ci.community/t/issue-with-python-2-6-on-linux/3861/2
    - python: 2.6
      dist: trusty
install:
  - pip install tox-travis
script:
  - tox
notifications:
  email:
    - stix-commits-list@groups.mitre.org
