name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      # matrix:
      #   python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        source /opt/venv/bin/activate
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
        cp -r . /app
        python /restart-threat-hunting-api-container.py
    # - name: Run Tests
    #   run: |
    #     python manage.py test
